version: 1
task: pose

labels:
  - name: object
    keypoints:
      - point1  # top-left
      - point2  # mid-left
      - point3  # bottom-left
      - point4  # top-right
      - point5  # mid-right
      - point6  # bottom-right
    skeleton:
      - [point1, point2]
      - [point2, point3]
      - [point4, point5]
      - [point5, point6]
      - [point1, point4]
      - [point2, point5]
      - [point3, point6]


